package com.himamis.retex.renderer.a;

import java.util.HashMap;

final class ca
{
  static
  {
    be.a.put("newcommand", new by(0, 2, 2));
    be.a.put("renewcommand", new by(1, 2, 2));
    be.a.put("rule", new by(2, 2, 1));
    be.a.put("hspace", new by(3, 1));
    be.a.put("vspace", new by(4, 1));
    be.a.put("llap", new by(5, 1));
    be.a.put("rlap", new by(6, 1));
    be.a.put("clap", new by(7, 1));
    be.a.put("mathllap", new by(8, 1));
    be.a.put("mathrlap", new by(9, 1));
    be.a.put("mathclap", new by(10, 1));
    be.a.put("includegraphics", new by(11, 1, 1));
    be.a.put("cfrac", new by(12, 2, 1));
    be.a.put("frac", new by(13, 2));
    be.a.put("sfrac", new by(14, 2));
    be.a.put("genfrac", new by(15, 6));
    be.a.put("over", new by(16, 0));
    be.a.put("overwithdelims", new by(17, 2));
    be.a.put("atop", new by(18, 0));
    be.a.put("atopwithdelims", new by(19, 2));
    be.a.put("choose", new by(20, 0));
    be.a.put("underscore", new by(21, 0));
    be.a.put("mbox", new by(22, 1));
    be.a.put("text", new by(23, 1));
    be.a.put("intertext", new by(24, 1));
    be.a.put("binom", new by(25, 2));
    be.a.put("mathbf", new by(26, 1));
    be.a.put("bf", new by(27, 0));
    be.a.put("mathbb", new by(28, 1));
    be.a.put("mathcal", new by(29, 1));
    be.a.put("cal", new by(30, 1));
    be.a.put("mathit", new by(31, 1));
    be.a.put("it", new by(32, 0));
    be.a.put("mathrm", new by(33, 1));
    be.a.put("rm", new by(34, 0));
    be.a.put("mathscr", new by(35, 1));
    be.a.put("mathsf", new by(36, 1));
    be.a.put("sf", new by(37, 0));
    be.a.put("mathtt", new by(38, 1));
    be.a.put("tt", new by(39, 0));
    be.a.put("mathfrak", new by(40, 1));
    be.a.put("mathds", new by(41, 1));
    be.a.put("frak", new by(42, 1));
    be.a.put("Bbb", new by(43, 1));
    be.a.put("oldstylenums", new by(44, 1));
    be.a.put("bold", new by(45, 1));
    be.a.put("^", new by(46, 1));
    be.a.put("'", new by(47, 1));
    be.a.put("\"", new by(48, 1));
    be.a.put("`", new by(49, 1));
    be.a.put("=", new by(50, 1));
    be.a.put(".", new by(51, 1));
    be.a.put("~", new by(52, 1));
    be.a.put("u", new by(53, 1));
    be.a.put("v", new by(54, 1));
    be.a.put("H", new by(55, 1));
    be.a.put("r", new by(56, 1));
    be.a.put("U", new by(57, 1));
    be.a.put("T", new by(58, 1));
    be.a.put("t", new by(59, 1));
    be.a.put("accent", new by(60, 2));
    be.a.put("grkaccent", new by(61, 2));
    be.a.put("hat", new by(62, 1));
    be.a.put("widehat", new by(63, 1));
    be.a.put("tilde", new by(64, 1));
    be.a.put("acute", new by(65, 1));
    be.a.put("grave", new by(66, 1));
    be.a.put("ddot", new by(67, 1));
    be.a.put("cyrddot", new by(68, 1));
    be.a.put("mathring", new by(69, 1));
    be.a.put("bar", new by(70, 1));
    be.a.put("breve", new by(71, 1));
    be.a.put("check", new by(72, 1));
    be.a.put("vec", new by(73, 1));
    be.a.put("dot", new by(74, 1));
    be.a.put("widetilde", new by(75, 1));
    be.a.put("nbsp", new by(76, 0));
    be.a.put("smallmatrix@@env", new by(77, 1));
    be.a.put("matrix@@env", new by(78, 1));
    be.a.put("overrightarrow", new by(79, 1));
    be.a.put("overleftarrow", new by(80, 1));
    be.a.put("overleftrightarrow", new by(81, 1));
    be.a.put("underrightarrow", new by(82, 1));
    be.a.put("underleftarrow", new by(83, 1));
    be.a.put("underleftrightarrow", new by(84, 1));
    be.a.put("xleftarrow", new by(85, 1, 1));
    be.a.put("xrightarrow", new by(86, 1, 1));
    be.a.put("underbrace", new by(87, 1));
    be.a.put("overbrace", new by(88, 1));
    be.a.put("underbrack", new by(89, 1));
    be.a.put("overbrack", new by(90, 1));
    be.a.put("underparen", new by(91, 1));
    be.a.put("overparen", new by(92, 1));
    be.a.put("sqrt", new by(93, 1, 1));
    be.a.put("sqrtsign", new by(94, 1));
    be.a.put("overline", new by(95, 1));
    be.a.put("underline", new by(96, 1));
    be.a.put("mathop", new by(97, 1));
    be.a.put("mathpunct", new by(98, 1));
    be.a.put("mathord", new by(99, 1));
    be.a.put("mathrel", new by(100, 1));
    be.a.put("mathinner", new by(101, 1));
    be.a.put("mathbin", new by(102, 1));
    be.a.put("mathopen", new by(103, 1));
    be.a.put("mathclose", new by(104, 1));
    be.a.put("joinrel", new by(105, 0));
    be.a.put("smash", new by(106, 1, 1));
    be.a.put("vdots", new by(107, 0));
    be.a.put("ddots", new by(108, 0));
    be.a.put("iddots", new by(109, 0));
    be.a.put("nolimits", new by(110, 0));
    be.a.put("limits", new by(111, 0));
    be.a.put("normal", new by(112, 0));
    be.a.put("(", new by(113, 0));
    be.a.put("[", new by(114, 0));
    be.a.put("left", new by(115, 1));
    be.a.put("middle", new by(116, 1));
    be.a.put("cr", new by(117, 0));
    be.a.put("multicolumn", new by(118, 3));
    be.a.put("hdotsfor", new by(119, 1, 1));
    be.a.put("array@@env", new by(120, 2));
    be.a.put("align@@env", new by(121, 2));
    be.a.put("aligned@@env", new by(122, 2));
    be.a.put("flalign@@env", new by(123, 2));
    be.a.put("alignat@@env", new by(124, 2));
    be.a.put("alignedat@@env", new by(125, 2));
    be.a.put("multline@@env", new by(126, 2));
    be.a.put("gather@@env", new by(127, 2));
    be.a.put("gathered@@env", new by(128, 2));
    be.a.put("shoveright", new by(129, 1));
    be.a.put("shoveleft", new by(130, 1));
    be.a.put("\\", new by(131, 0));
    be.a.put("newenvironment", new by(132, 3));
    be.a.put("renewenvironment", new by(133, 3));
    be.a.put("makeatletter", new by(134, 0));
    be.a.put("makeatother", new by(135, 0));
    be.a.put("fbox", new by(136, 1));
    be.a.put("boxed", new by(137, 1));
    be.a.put("stackrel", new by(138, 2, 1));
    be.a.put("stackbin", new by(139, 2, 1));
    be.a.put("accentset", new by(140, 2));
    be.a.put("underaccent", new by(141, 2));
    be.a.put("undertilde", new by(142, 1));
    be.a.put("overset", new by(143, 2));
    be.a.put("Braket", new by(144, 1));
    be.a.put("Set", new by(145, 1));
    be.a.put("underset", new by(146, 2));
    be.a.put("boldsymbol", new by(147, 1));
    be.a.put("LaTeX", new by(148, 0));
    be.a.put("GeoGebra", new by(149, 0));
    be.a.put("big", new by(150, 1));
    be.a.put("Big", new by(151, 1));
    be.a.put("bigg", new by(152, 1));
    be.a.put("Bigg", new by(153, 1));
    be.a.put("bigl", new by(154, 1));
    be.a.put("Bigl", new by(155, 1));
    be.a.put("biggl", new by(156, 1));
    be.a.put("Biggl", new by(157, 1));
    be.a.put("bigr", new by(158, 1));
    be.a.put("Bigr", new by(159, 1));
    be.a.put("biggr", new by(160, 1));
    be.a.put("Biggr", new by(161, 1));
    be.a.put("displaystyle", new by(162, 0));
    be.a.put("textstyle", new by(163, 0));
    be.a.put("scriptstyle", new by(164, 0));
    be.a.put("scriptscriptstyle", new by(165, 0));
    be.a.put("sideset", new by(166, 3));
    be.a.put("prescript", new by(167, 3));
    be.a.put("rotatebox", new by(168, 2, 1));
    be.a.put("reflectbox", new by(169, 1));
    be.a.put("scalebox", new by(170, 2, 2));
    be.a.put("resizebox", new by(171, 3));
    be.a.put("raisebox", new by(172, 2, 2));
    be.a.put("shadowbox", new by(173, 1));
    be.a.put("ovalbox", new by(174, 1));
    be.a.put("doublebox", new by(175, 1));
    be.a.put("phantom", new by(176, 1));
    be.a.put("hphantom", new by(177, 1));
    be.a.put("vphantom", new by(178, 1));
    be.a.put("sp@breve", new by(179, 0));
    be.a.put("sp@hat", new by(180, 0));
    be.a.put("definecolor", new by(181, 3));
    be.a.put("textcolor", new by(182, 2));
    be.a.put("fgcolor", new by(183, 2));
    be.a.put("bgcolor", new by(184, 2));
    be.a.put("colorbox", new by(185, 2));
    be.a.put("fcolorbox", new by(186, 3));
    be.a.put("c", new by(187, 1));
    be.a.put("IJ", new by(188, 0));
    be.a.put("ij", new by(189, 0));
    be.a.put("TStroke", new by(190, 0));
    be.a.put("tStroke", new by(191, 0));
    be.a.put("Lcaron", new by(192, 0));
    be.a.put("tcaron", new by(193, 0));
    be.a.put("lcaron", new by(194, 0));
    be.a.put("k", new by(195, 1));
    be.a.put("cong", new by(196, 0));
    be.a.put("doteq", new by(197, 0));
    be.a.put("jlmDynamic", new by(198, 1, 1));
    be.a.put("jlmExternalFont", new by(199, 1));
    be.a.put("jlmText", new by(200, 1));
    be.a.put("jlmTextit", new by(201, 1));
    be.a.put("jlmTextbf", new by(202, 1));
    be.a.put("jlmTextitbf", new by(203, 1));
    be.a.put("DeclareMathSizes", new by(204, 4));
    be.a.put("magnification", new by(205, 1));
    be.a.put("hline", new by(206, 0));
    be.a.put("tiny", new by(207, 0));
    be.a.put("scriptsize", new by(208, 0));
    be.a.put("footnotesize", new by(209, 0));
    be.a.put("small", new by(210, 0));
    be.a.put("normalsize", new by(211, 0));
    be.a.put("large", new by(212, 0));
    be.a.put("Large", new by(213, 0));
    be.a.put("LARGE", new by(214, 0));
    be.a.put("huge", new by(215, 0));
    be.a.put("Huge", new by(216, 0));
    be.a.put("jlatexmathcumsup", new by(217, 1));
    be.a.put("jlatexmathcumsub", new by(218, 1));
    be.a.put("hstrok", new by(219, 0));
    be.a.put("Hstrok", new by(220, 0));
    be.a.put("dstrok", new by(221, 0));
    be.a.put("Dstrok", new by(222, 0));
    be.a.put("dotminus", new by(223, 0));
    be.a.put("ratio", new by(224, 0));
    be.a.put("smallfrowneq", new by(225, 0));
    be.a.put("geoprop", new by(226, 0));
    be.a.put("minuscolon", new by(227, 0));
    be.a.put("minuscoloncolon", new by(228, 0));
    be.a.put("simcolon", new by(229, 0));
    be.a.put("simcoloncolon", new by(230, 0));
    be.a.put("approxcolon", new by(231, 0));
    be.a.put("approxcoloncolon", new by(232, 0));
    be.a.put("coloncolon", new by(233, 0));
    be.a.put("equalscolon", new by(234, 0));
    be.a.put("equalscoloncolon", new by(235, 0));
    be.a.put("colonminus", new by(236, 0));
    be.a.put("coloncolonminus", new by(237, 0));
    be.a.put("colonequals", new by(238, 0));
    be.a.put("coloncolonequals", new by(239, 0));
    be.a.put("colonsim", new by(240, 0));
    be.a.put("coloncolonsim", new by(241, 0));
    be.a.put("colonapprox", new by(242, 0));
    be.a.put("coloncolonapprox", new by(243, 0));
    be.a.put("kern", new by(244, 1));
    be.a.put("char", new by(245, 1));
    be.a.put("roman", new by(246, 1));
    be.a.put("Roman", new by(247, 1));
    be.a.put("textcircled", new by(248, 1));
    be.a.put("textsc", new by(249, 1));
    be.a.put("sc", new by(250, 0));
    be.a.put(",", new by(251, 0));
    be.a.put(":", new by(252, 0));
    be.a.put(";", new by(253, 0));
    be.a.put("thinspace", new by(254, 0));
    be.a.put("medspace", new by(255, 0));
    be.a.put("thickspace", new by(256, 0));
    be.a.put("!", new by(257, 0));
    be.a.put("negthinspace", new by(258, 0));
    be.a.put("negmedspace", new by(259, 0));
    be.a.put("negthickspace", new by(260, 0));
    be.a.put("quad", new by(261, 0));
    be.a.put("surd", new by(262, 0));
    be.a.put("iint", new by(263, 0));
    be.a.put("iiint", new by(264, 0));
    be.a.put("iiiint", new by(265, 0));
    be.a.put("idotsint", new by(266, 0));
    be.a.put("int", new by(267, 0));
    be.a.put("oint", new by(268, 0));
    be.a.put("lmoustache", new by(269, 0));
    be.a.put("rmoustache", new by(270, 0));
    be.a.put("-", new by(271, 0));
    be.a.put("jlmXML", new by(272, 1));
    be.a.put("above", new by(273, 0));
    be.a.put("abovewithdelims", new by(274, 2));
    be.a.put("st", new by(275, 1));
    be.a.put("fcscore", new by(276, 1));
  }
}

/* Location:           C:\Androidnixiangzhushou\zikao_classes_dex2jar.jar
 * Qualified Name:     com.himamis.retex.renderer.a.ca
 * JD-Core Version:    0.6.0
 */